# Generated by Django 2.2 on 2019-05-11 12:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity_99', models.IntegerField()),
                ('director', models.CharField(max_length=200)),
                ('genre', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=2010, size=10)),
                ('imdb_score', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
